language: node_js
node_js: "8"
os:
  - linux

cache:
  yarn: true

before_install:
- sudo apt-get -qq update
- sudo apt-get install --no-install-recommends -y icnsutils graphicsmagick xz-utils

install:
- yarn

script:
  - npm run pack
